### ISSUE TITLE
Custom search engine compiles, but isn't found by snort

### ISSUE THREAD

**Issue by vlad-ulmeanu01** [snort3/snort3_extra#12]
I copy-pasted the `lowmem` search-engine plugin example, and minimally modified it (resulting in a plugin named `bruteforce`).

The directory layout looks like this:
```
snort3_extra/src/search_engines/
                                bruteforce/bruteforce.cc
                                           CMakeLists.txt
                                lowmem/...
                                CMakeLists.txt
```

The modified files from the directory:
- [bruteforce.cc](https://github.com/snort3/snort3_extra/files/14396540/bruteforce_cc.txt)
- The modified `CMakeLists.txt` file in `bruteforce/`: [CMakeLists.txt](https://github.com/snort3/snort3_extra/files/14396557/CMakeLists.txt)
- The modified `CMakeLists.txt` file in `search_engines/`: [CMakeLists.txt](https://github.com/snort3/snort3_extra/files/14396561/CMakeLists.txt)

After repeating the 3rd step in the README (Compile and install: `./configure_cmake.sh`, `cd build`, `make`, `make install`), the shared object files for both `lowmem` and `bruteforce` were generated without any errors:

```
-- Installing: /usr/local/snort/lib/snort/plugins/extra/search_engines/lowmem.so
-- Installing: /usr/local/snort/lib/snort/plugins/extra/search_engines/bruteforce.so
```

However, only `lowmem` is recognized when attempting to list any extra plugins:
```
> snort --plugin-path /usr/local/snort/lib/snort/plugins/extra --list-plugins | grep search_engine
search_engine::ac_bnfa v0 static
search_engine::ac_full v0 static
search_engine::lowmem v0 /usr/local/snort/lib/snort/plugins/extra/search_engines/lowmem.so
```

Even if `bruteforce.so` is in the same folder as `lowmem.so`:
```
> ls /usr/local/snort/lib/snort/plugins/extra/search_engines/
bruteforce.so  lowmem.so
```

I can't figure out what I'm missing. Thank you for helping.

**Comment by niflostancu** [comment]
Hello,

Did you export a `snort_plugins` symbol pointing to your custom API object?

This the actual "entry point" of the plugin's dynamic library.

See [the example here](https://github.com/snort3/snort3_extra/blob/master/src/search_engines/lowmem/trie_api.cc) ;)
