### ISSUE TITLE
issue during 'make' step - get_netbios

### ISSUE THREAD

**Issue by marko-kovacevic** [snort3/snort3_extra#4]
Hello,

I'm following the steps to build snort3_extras, and at the 'make' command I have an error that is preventing me from building it.

Below are the following errors.

Using latest version of Snort on Ubuntu 20.04

`/home/marko/snort_src/snort3_extra/src/inspectors/appid_listener/appid_listener_event_handler.cc: In member function ‘virtual void AppIdListenerEventHandler::handle(snort::DataEvent&, snort::Flow*)’:
/home/marko/snort_src/snort3_extra/src/inspectors/appid_listener/appid_listener_event_handler.cc:81:36: error: ‘const class snort::AppIdSessionApi’ has no member named ‘get_netbios_name’
   81 |     const char *netbios_name = api.get_netbios_name();
      |                                    ^~~~~~~~~~~~~~~~
/home/marko/snort_src/snort3_extra/src/inspectors/appid_listener/appid_listener_event_handler.cc:82:38: error: ‘const class snort::AppIdSessionApi’ has no member named ‘get_netbios_domain’
   82 |     const char *netbios_domain = api.get_netbios_domain();
      |                                      ^~~~~~~~~~~~~~~~~~
make[2]: *** [src/inspectors/appid_listener/CMakeFiles/appid_listener.dir/build.make:76: src/inspectors/appid_listener/CMakeFiles/appid_listener.dir/appid_listener_event_handler.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1054: src/inspectors/appid_listener/CMakeFiles/appid_listener.dir/all] Error 2
make: *** [Makefile:152: all] Error 2`

**Comment by katharve** [comment]
Can you double check you've pulled in and rebuilt the latest version of Snort? Those two functions have been added to Snort3 over the past couple months, so it looks like you probably have an older version of snort3 than snort3_extra.

**Comment by marko-kovacevic** [comment]
> Can you double check you've pulled in and rebuilt the latest version of Snort? Those two functions have been added to Snort3 over the past couple months, so it looks like you probably have an older version of snort3 than snort3_extra.

Thank you for responding! I do have a slightly older version of Snort, my mistake. Having some errors building the newest version, but I'll try again later. I imagine that is likely my issue.

Thank you again!

**Comment by adrputra** [comment]
So what version of snort3 is supported by snort3_extra exactly? I'm using snort 3.1.0.0 and got the exact same problem

**Comment by adrputra** [comment]
> 
> 
> Can you double check you've pulled in and rebuilt the latest version of Snort? Those two functions have been added to Snort3 over the past couple months, so it looks like you probably have an older version of snort3 than snort3_extra.

So what version of snort3 is supported by snort3_extra exactly? I'm using snort 3.1.0.0 and got the exact same problem

**Comment by snortadmin** [comment]
Generally, pulling master from each repo will get you what you want. To be precise, use tags. Eg, snort3, snort3_extra, snort3_demo are all currently tagged at the latest release which 3.1.5.0.
