### ISSUE TITLE
None of the required 'snort>=3' found

### ISSUE THREAD

**Issue by xyyy1420** [snort3/snort3_extra#7]
I'm installing snort extra as described in the “Snort_3_GA_on_CentOS_8_Stream” but I get some error.There are many errors similar to this.Any help is greatly appreciated.

```
-- Checking for one of the modules 'snort>=3'
CMake Error at /usr/share/cmake/Modules/FindPkgConfig.cmake:843 (message):
  None of the required 'snort>=3' found
Call Stack (most recent call first):
  src/CMakeLists.txt:13 (pkg_search_module)

```

**Comment by vlad-ulmeanu01** [comment]
In case somebody else stumbles upon this, `pkg-config` refused to find `snort>=3` in my case because I ran `./configure_cmake.sh` with `sudo` privileges.
